--- #YAML:1.0
name:                Unicode-RecursiveDowngrade
version:             0.04
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    bytes:                         0
    Test::More:                    0.32
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
